<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Arya Satya Pratama">
<meta name="dcterms.date" content="2024-01-20">

<title>Pengaruh Produksi Beras Lokal terhadap Impor Beras di Indonesia Tahun 2000 Hingga 2022</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="index_files/libs/clipboard/clipboard.min.js"></script>
<script src="index_files/libs/quarto-html/quarto.js"></script>
<script src="index_files/libs/quarto-html/popper.min.js"></script>
<script src="index_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="index_files/libs/quarto-html/anchor.min.js"></script>
<link href="index_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="index_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="index_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="index_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="index_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="index.docx"><i class="bi bi-file-word"></i>MS Word</a></li></ul></div></div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Pengaruh Produksi Beras Lokal terhadap Impor Beras di Indonesia Tahun 2000 Hingga 2022</h1>
<p class="subtitle lead">Metode Penelitian Politeknik APP Jakarta</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Arya Satya Pratama </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">January 20, 2024</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<p><img src="poltekapp.jpg" class="img-fluid"></p>
<section id="pendahuluan" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="pendahuluan"><span class="header-section-number">1</span> Pendahuluan</h2>
<section id="latar-belakang" class="level3" data-number="1.1">
<h3 data-number="1.1" class="anchored" data-anchor-id="latar-belakang"><span class="header-section-number">1.1</span> Latar belakang</h3>
<p>Beras merupakan salah satu makanan pokok manusia terutama yang hidup di negara negara Asia, termasuk Indonesia. sehingga tidak heran jika konsumsi dan kebutuhan akan beras di Indonesia dan negara negara lain yang menjadikan beras menjadi sumber karbohidrat pokok menjadi yang utama untuk di konsumsi. tidak heran jika beras menjadi komoditi terpenting bagi Indonesia terutama untuk kepentingan masyarakat nya sebagai konsumsi, dan beras Indonesia pun bisa digunakan untuk kepentingan ekspor Indonesia.</p>
<p>Beras merupakan gabah (butiran padi) yang bagian kulit luarnya sudah dibuang dengan cara digiling atau disosoh. Cita rasa dan mutu masak dari beras ditentukan oleh banyaknya kadar amilosa dan amilopektinnya. dan juga cara memasak dari beras itu sendiri yang dapat mempengaruhi bagaimana rasa dan tekstur dari beras yang akan di konsumsi. sehingga beras tersebut dapat disajikan dan dimakan lebih nikmat oleh seluruh kalangan masyarakat.</p>
<p>bagi masyarakat Indonesia, beras menjadi faktor utama dalam memulai segala aktifitas. beras yang sudah diolah menjadi nasi menjadi makanan pokok utama yang dapat disajikan dengan beberapa lauk yang merupakan hasil dari komoditi Indonesia juga. memakan nasi bukan hanya menjadi makanan pokok orang orang Indonesia, namun sudah menjadi habbit/kebiasaan orang orang Indonesia untuk memulai hari. bahkan terkadang ada omongan seperti makan apapun belum cukup jika tidak makan nasi. itu menjadi kebiasaan orang Indonesia yang menganggap bahwa makan adalah ketika sudah memakan nasi.</p>
<p>Karena nasi juga sudah menjadi makanan utama yang tidak hanya di konsumsi oleh orang dewasa namun juga dikonsumsi semua kalangan usia, dari anak kecil, remaja, dewasa hingga lansia sekalipun. karena kebiasaan memakan nasi tersebut yang sudah di turunkan dari tahun ke tahun yang menjadikan nya terus bertahan hingga sekarang. Padahal sumber karbohidrat utama tidak hanya didapatkan dari nasi saja namun juga bisa dari singkong, umbi umbian namun tetap saja nasi selalu menjadi yang paling dicari oleh orang- orang Indonesia. faktor tersebutlah yang membuat mengapa pemerintah Indonesia tetap membutuhkan impor beras dari negara luar untuk memenuhi kebutuhan konsumsi masyarakat terhadap beras. dan juga import tersebut juga bertujuan untuk menjaga kestabilan beras lokal dan juga menjaga kestabilan harga beras tersebut. beras lokal juga tidak kehabisan stok jika sewaktu-waktu terdapat situasi dan kondisi yang darurat pangan.</p>
</section>
<section id="ruang-lingkup" class="level3" data-number="1.2">
<h3 data-number="1.2" class="anchored" data-anchor-id="ruang-lingkup"><span class="header-section-number">1.2</span> Ruang lingkup</h3>
<p>Ada dua variabel yang digunakan sebagai objek penelitian, yaitu objek data berupa produksi beras lokal di Indonesia sebagai variabel x, serta data objek impor beras Indonesia sebagai variabel y. Peneliti mengambil data dari Badan Pusat Statistik (BPS), dengan data bersifat time series dalam kurun waktu periode 2000 hingga 2022.</p>
</section>
<section id="rumusan-masalah" class="level3" data-number="1.3">
<h3 data-number="1.3" class="anchored" data-anchor-id="rumusan-masalah"><span class="header-section-number">1.3</span> Rumusan masalah</h3>
<ol type="a">
<li><p>Apakah produksi beras lokal mempengaruhi impor beras di Indonesia ?</p></li>
<li><p>Bagaimana hubungan produksi beras lokal dan impor beras di Indonesia ?</p></li>
</ol>
</section>
<section id="tujuan-dan-manfaat-penelitian" class="level3" data-number="1.4">
<h3 data-number="1.4" class="anchored" data-anchor-id="tujuan-dan-manfaat-penelitian"><span class="header-section-number">1.4</span> Tujuan dan manfaat penelitian</h3>
<p>Penelitian ini bertujuan untuk mengkaji pengaruh produksi beras lokal terhadap impor beras di Indonesia selama periode 2000-2022. Manfaat penelitian ini adalah untuk memberikan informasi dan rekomendasi kepada pemerintah dan pelaku usaha dalam mengelola kebijakan impor beras yang sesuai dengan kondisi produksi dan konsumsi beras di dalam negeri. Penelitian ini juga diharapkan dapat memberikan kontribusi bagi pengembangan ilmu ekonomi, khususnya dalam bidang perdagangan internasional dan pertanian.</p>
</section>
<section id="package" class="level3" data-number="1.5">
<h3 data-number="1.5" class="anchored" data-anchor-id="package"><span class="header-section-number">1.5</span> Package</h3>
<p>Packages yang digunakan antara lain sebagai berikut:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(writexl)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(kableExtra)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="studi-pustaka" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="studi-pustaka"><span class="header-section-number">2</span> Studi pustaka</h2>
<p><strong>Kebijakan Pangan Nasional</strong></p>
<p>Rumah tangga Indonesia, khususnya rumah tangga pertanian, paling sering terkena ancaman berupa hilangnya produksi non-pertanian dan hilangnya lapangan kerja, sehingga berdampak pada berkurangnya pendapatan rumah tangga sehingga terjaminnya ketahanan pangan. Produksi dan pendapatan rumah tangga hanya mampu memenuhi kebutuhan pangan dalam jumlah cukup, dan dalam beberapa kasus, beberapa rumah tangga tidak mampu memenuhi kebutuhan sehari-harinya. Petani seringkali tidak mempunyai kapasitas untuk mengatasi krisis pangan dan pendapatan.</p>
<p><strong>Ketersediaan Beras Nasional</strong></p>
<p>Badan Pangan Nasional (Bapanas) memperkirakan stok akhir beras di negara ini akan mencapai 7,69 juta ton pada akhir tahun 2023. Jumlah tersebut merupakan stok awal beras yang diproduksi pada tahun 2024 dan masa kadaluwarsanya adalah 93 hari. Sedangkan persediaan akhir periode ditentukan dari perkiraan total pasokan beras sebanyak 58,53 juta ton hingga akhir Desember 2023. Angka tersebut dihitung dari persediaan awal sebanyak 4,06 juta ton pada tahun 2023. Dengan demikian perkiraan produksi beras Januari-Desember 2023 adalah 31,56 juta ton. Dan diperkirakan Indonesia akan mengimpor beras sebanyak 2,91 juta ton pada tahun ini. Data ini dikurangi dengan kebutuhan beras Indonesia yang diperkirakan mencapai 30,84 juta ton pada tahun 2023. Sedangkan rata-rata kebutuhan beras per bulan sebesar 2,57 juta ton. Melihat besarnya jumlah kebutuhan konsumsi beras nasional di atas, memang butuh ketersediaan komoditi beras yang menjadi sumber utama kebutuhan orang Indonesia, sehingga lazim bagi pemerintah Indonesia untuk tetap melakukan impor beras ke negara lain, untuk memenuhi kebutuhan akan besarnya kebutuhan beras masyarakat Indonesia yang menjadikan nasi sebagai karbohidrat utama di atas komoditi yang lain.</p>
</section>
<section id="metode-penelitian" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="metode-penelitian"><span class="header-section-number">3</span> Metode penelitian</h2>
<section id="data" class="level3" data-number="3.1">
<h3 data-number="3.1" class="anchored" data-anchor-id="data"><span class="header-section-number">3.1</span> Data</h3>
<table class="table">
<thead>
<tr class="header">
<th></th>
<th>Tahun</th>
<th>PBL</th>
<th>IB</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>2000</td>
<td>31,9</td>
<td>1,4</td>
</tr>
<tr class="even">
<td>2</td>
<td>2001</td>
<td>32,8</td>
<td>0,6</td>
</tr>
<tr class="odd">
<td>3</td>
<td>2002</td>
<td>34,7</td>
<td>1,8</td>
</tr>
<tr class="even">
<td>4</td>
<td>2003</td>
<td>35,5</td>
<td>1,4</td>
</tr>
<tr class="odd">
<td>5</td>
<td>2004</td>
<td>36,4</td>
<td>0,2</td>
</tr>
<tr class="even">
<td>6</td>
<td>2005</td>
<td>37,3</td>
<td>0,2</td>
</tr>
<tr class="odd">
<td>7</td>
<td>2006</td>
<td>38,4</td>
<td>0,4</td>
</tr>
<tr class="even">
<td>8</td>
<td>2007</td>
<td>39,7</td>
<td>1,4</td>
</tr>
<tr class="odd">
<td>9</td>
<td>2008</td>
<td>40,1</td>
<td>0,3</td>
</tr>
<tr class="even">
<td>10</td>
<td>2009</td>
<td>40,6</td>
<td>0,3</td>
</tr>
<tr class="odd">
<td>11</td>
<td>2010</td>
<td>41,9</td>
<td>0,7</td>
</tr>
<tr class="even">
<td>12</td>
<td>2011</td>
<td>43,3</td>
<td>2,8</td>
</tr>
<tr class="odd">
<td>13</td>
<td>2012</td>
<td>44,1</td>
<td>1,8</td>
</tr>
<tr class="even">
<td>14</td>
<td>2013</td>
<td>44,9</td>
<td>0,5</td>
</tr>
<tr class="odd">
<td>15</td>
<td>2014</td>
<td>45,3</td>
<td>0,8</td>
</tr>
<tr class="even">
<td>16</td>
<td>2015</td>
<td>45,9</td>
<td>0,9</td>
</tr>
<tr class="odd">
<td>17</td>
<td>2016</td>
<td>46,7</td>
<td>1,3</td>
</tr>
<tr class="even">
<td>18</td>
<td>2017</td>
<td>47,2</td>
<td>0,3</td>
</tr>
<tr class="odd">
<td>19</td>
<td>2018</td>
<td>47,6</td>
<td>2,3</td>
</tr>
<tr class="even">
<td>20</td>
<td>2019</td>
<td>48</td>
<td>0,4</td>
</tr>
<tr class="odd">
<td>21</td>
<td>2020</td>
<td>48,3</td>
<td>0,4</td>
</tr>
<tr class="even">
<td>22</td>
<td>2021</td>
<td>48,5</td>
<td>0,3</td>
</tr>
<tr class="odd">
<td>23</td>
<td>2022</td>
<td>49</td>
<td>0,3</td>
</tr>
</tbody>
</table>
<p>Data yang digunakan bersifat time series periode tahun 2000 hingga 2022 yang diambil dari Badan Pusat Statistik (BPS) berupa produksi beras lokal (PBL) dan impor beras (IB) di Indonesia dalam juta ton, sehingga didapatkan data produksi beras sebagai variabel x dan data impor beras sebagai variabel y. Data inilahh yang nantinya akan digunakan sebagai objek penelitian.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>berasarya<span class="ot">&lt;-</span><span class="fu">read_excel</span>(<span class="st">"C:/metopen/uasarya/berasarya.xlsx"</span>)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(berasarya)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 3
  Tahun     x     y
  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
1  2000  31.9   1.4
2  2001  32.8   0.6
3  2002  34.7   1.8
4  2003  35.5   1.4
5  2004  36.4   0.2
6  2005  37.3   0.2</code></pre>
</div>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"ggplot2"</span>)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"readxl"</span>)</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"dplyr"</span>)</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span>berasarya,<span class="fu">aes</span>(<span class="at">x=</span>x,<span class="at">y=</span>y))<span class="sc">+</span></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">color=</span><span class="st">"blue"</span>,<span class="at">size=</span><span class="dv">2</span>)<span class="sc">+</span></span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title=</span><span class="st">"hubungan produksi beras lokal dan impor beras"</span>,</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">x=</span><span class="st">"produksi beras lokal"</span>,</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">y=</span><span class="st">"impor beras"</span>,</span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>       <span class="at">caption =</span> <span class="st">"sumber: Badan Pusat Statistik"</span>)<span class="sc">+</span></span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="metode-analisis" class="level3" data-number="3.2">
<h3 data-number="3.2" class="anchored" data-anchor-id="metode-analisis"><span class="header-section-number">3.2</span> Metode analisis</h3>
<p>Metode analisis yang digunakan dalam penelitian ini adalah metode regresi univariat. Metode ini digunakan untuk menguji pengaruh variabel independen terhadap variabel dependen secara statistik. Variabel independen dalam penelitian ini adalah produksi beras lokal, sedangkan variabel dependen adalah impor beras. Data produksi dan impor beras di Indonesia dari tahun 2000 hingga 2022 diperoleh dari Badan Pusat Statistik (BPS). Spesifikasi yang dilakukan sebagai berikut:</p>
<p><span class="math display">\[
y_{t}=\beta_0 + \beta_1 x_t+\mu_t
\]</span> di mana <span class="math inline">\(y_t\)</span> adalah impor beras dan <span class="math inline">\(x_t\)</span> adalah produksi beras lokal.</p>
</section>
</section>
<section id="pembahasan" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="pembahasan"><span class="header-section-number">4</span> Pembahasan</h2>
<section id="pembahasan-masalah" class="level3" data-number="4.1">
<h3 data-number="4.1" class="anchored" data-anchor-id="pembahasan-masalah"><span class="header-section-number">4.1</span> Pembahasan masalah</h3>
<p>Hasil regresi:</p>
<table class="table">
<thead>
<tr class="header">
<th>Coefficients</th>
<th>Estimate</th>
<th>Pr</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Intercept</td>
<td>1.36206</td>
<td>0.289</td>
</tr>
<tr class="even">
<td>x</td>
<td>-0.01087</td>
<td>0.716</td>
</tr>
</tbody>
</table>
<p>Hasil dimasukkan ke dalam rumus persamaan dan menghasilkan:</p>
<p><span class="math display">\[
y_{t}=\  1.36206 - \ 0.01087 x+\mu_t
\]</span></p>
<p>Nilai koefisien regresi β1​ menunjukkan bahwa setiap kenaikan satu ton produksi beras lokal akan menurunkan impor beras sebesar 0.01087 ton, dengan asumsi variabel lain konstan.</p>
<p>Nilai p-value untuk β1​ adalah 0.716, yang berarti tidak ada bukti yang cukup untuk menolak hipotesis nol bahwa produksi beras lokal tidak berpengaruh terhadap impor beras. Dengan kata lain, tidak ada hubungan yang signifikan antara produksi beras lokal dan impor beras pada tingkat signifikansi 5%.</p>
</section>
<section id="analisis-masalah" class="level3" data-number="4.2">
<h3 data-number="4.2" class="anchored" data-anchor-id="analisis-masalah"><span class="header-section-number">4.2</span> Analisis masalah</h3>
<p>Hasil regresinya adalah</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>berasarya<span class="ot">&lt;-</span><span class="fu">read_excel</span>(<span class="st">"berasarya.xlsx"</span>)</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>reg<span class="ot">&lt;-</span><span class="fu">lm</span>(y<span class="sc">~</span>x,<span class="at">data=</span>berasarya)</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(reg)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = y ~ x, data = berasarya)

Residuals:
    Min      1Q  Median      3Q     Max 
-0.7662 -0.5396 -0.3738  0.4349  1.9088 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)
(Intercept)  1.36206    1.25274   1.087    0.289
x           -0.01087    0.02953  -0.368    0.716

Residual standard error: 0.7513 on 21 degrees of freedom
Multiple R-squared:  0.006416,  Adjusted R-squared:  -0.0409 
F-statistic: 0.1356 on 1 and 21 DF,  p-value: 0.7164</code></pre>
</div>
</div>
<p>Nilai R-squared adalah 0.006416, yang berarti bahwa hanya 0.64% variasi impor beras yang dapat dijelaskan oleh variasi produksi beras lokal. Nilai ini sangat rendah, yang mengindikasikan bahwa model regresi tidak memiliki kemampuan prediksi yang baik.</p>
<p>Sedangkan nilai F-statistic adalah 0.1356, yang berarti bahwa model regresi secara keseluruhan tidak signifikan pada tingkat signifikansi 5%. Hal ini mengkonfirmasi bahwa produksi beras lokal tidak berpengaruh terhadap impor beras.</p>
</section>
</section>
<section id="kesimpulan" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="kesimpulan"><span class="header-section-number">5</span> Kesimpulan</h2>
<p>Dari analisis di atas, dapat disimpulkan bahwa model regresi univariat yang digunakan dalam penelitian ini tidak sesuai dengan data dan tidak dapat digunakan untuk menguji pengaruh produksi beras lokal terhadap impor beras di Indonesia. Peneliti perlu mencari variabel lain yang mungkin berpengaruh terhadap impor beras, atau menggunakan metode analisis yang lebih kompleks, seperti regresi multivariat atau regresi non-linier.</p>
<p>Faktor yang mungkin menyebabkan Produksi beras lokal tidak mempengaruhi impor beras Indonesia, karena impor beras lebih ditentukan oleh faktor-faktor lain, seperti:</p>
<p>Permintaan beras yang terus meningkat seiring dengan pertumbuhan penduduk, sementara produksi beras tidak mampu mengimbangi kebutuhan. Hal ini menyebabkan kekurangan pasokan beras di dalam negeri, sehingga pemerintah harus mengimpor beras dari luar negeri untuk memenuhi kebutuhan konsumen.</p>
<p>Harga beras yang lebih tinggi daripada harga beras impor, sehingga menguntungkan para importir dan pedagang. Hal ini menyebabkan ketidakberdayaan produsen beras lokal, yang harus bersaing dengan harga beras impor yang lebih murah. Selain itu, harga beras lokal juga dipengaruhi oleh biaya produksi yang tinggi, seperti biaya pupuk, benih, irigasi, tenaga kerja, dan transportasi.</p>
<p>Kurs rupiah yang melemah terhadap mata uang asing, sehingga membuat impor beras lebih murah. Hal ini menyebabkan ketergantungan Indonesia terhadap beras impor, terutama dari negara-negara seperti Vietnam, Thailand, India, dan Pakistan. Kurs rupiah juga dipengaruhi oleh faktor eksternal, seperti kondisi politik, ekonomi, dan sosial di dunia.</p>
<p>Luas lahan panen padi yang terbatas dan mengalami penurunan akibat alih fungsi lahan, bencana alam, dan perubahan iklim. Hal ini menyebabkan penurunan produktivitas beras lokal, yang tidak sebanding dengan pertumbuhan penduduk. Lahan panen padi juga dipengaruhi oleh faktor internal, seperti kebijakan pemerintah, infrastruktur, teknologi, dan sumber daya manusia.</p>
</section>
<section id="referensi" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="referensi"><span class="header-section-number">6</span> Referensi</h2>
<p>Armaini, D., &amp; Gunawan, E. (2016). Pengaruh produksi beras, harga beras dalam negeri dan produk domestik bruto terhadap impor beras Indonesia. Jurnal ilmiah mahasiswa ekonomi pembangunan, 1(2), 455-466.</p>
<p>Ruvananda, A. R., &amp; Taufiq, M. (2022). Analisis faktor-faktor yang mempengaruhi impor beras di Indonesia. KINERJA: Jurnal Ekonomi dan Manajemen, 19(2), 195-204.</p>
<p>Sanny, L. (2010). Analisis produksi beras di Indonesia. Binus Business Review, 1(1), 245-251.</p>
<p>Rahayu, S. E., &amp; Febriaty, H. (2019, October). Analisis perkembangan produksi beras dan impor beras di Indonesia. In Prosiding Seminar Nasional Kewirausahaan (Vol. 1, No.&nbsp;1, pp.&nbsp;219-226).</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>